import math
#game settings

RES = WIDTH, HEIGHT = 1600, 900
FPS = 120
FOV = math.pi / 3
HALF_FOV = FOV / 2
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

####### PLAYER CONFIG
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 4
PLAYER_ROT_SPEED = 2
PLAYER_RADIUS = .2
PLAYER_SIZE_SCALE =  60
PLAYER_MAX_HEALTH = 100

####### RAY CASTING CONFIG

NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_RAY_DEPTH = 200

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

### TEXTURING

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2