import math
#game settings

RES = WIDTH, HEIGHT = 1600, 900
FPS = 60
FOV = math.pi / 3
HALF_FOV = FOV / 2

####### PLAYER CONFIG
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 4
PLAYER_ROT_SPEED = 2
PLAYER_RADIUS = .2

####### RAY CASTING CONFIG

NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_RAY_DEPTH = 20